FROM nginx:latest
# Copy the Angular build unde nginx
COPY ./dist/mymovie-frontend /usr/share/nginx/html
# Copy Nginx config file
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
# Expose port 80
EXPOSE 80
# Start nginx in foreground
CMD nginx -g "daemon off;"